### ISSUE TITLE
Test::README Overwrites File From Test-MockObject

### ISSUE THREAD

**Issue by theory** [briandfoy/test-file#12]
Probably both have the same issue: They install the `README.pod` as `Test::README`. I suggest adding something to `Makefile.PL` to exclude `README.pod` from installation.

**Comment by theory** [comment]
I've reported this issue for Test-MockObject [here](https://rt.cpan.org/Ticket/Display.html?id=105297). Looks like it could be fixed by the use of an `INSTALL.SKIP` file, which will be read by [ExtUtils::Install](http://perldoc.perl.org/ExtUtils/Install.html).

**Comment by karenetheridge** [comment]
I've approached this problem by never shipping a README.pod -- I only generate one for the github repository, but exclude it from being packaged into the tarball entirely, since it is redundant with the main documentation's pod anyway.

Another option is generating a README.md instead of .pod, which PAUSE and installers (EUMM etc) do not treat as installable library files.

**Comment by briandfoy** [comment]
INSTALL.SKIP didn't seem to work, but we'll see what happens with 1.43.

**Comment by karenetheridge** [comment]
> INSTALL.SKIP didn't seem to work

Do you have details/a bug report? I can poke the appropriate toolchain folks.

**Comment by briandfoy** [comment]
I think this is fixed now.

**Comment by kentfredric** [comment]
> INSTALL.SKIP didn't seem to work, but we'll see what happens with 1.43.

INSTALL.SKIP may give the impression of not working, because EUMM still copes the target file from $ROOT to $ROOT/blib/ 

However INSTALL.SKIP is a rule set that filters *blib* -> `$TARGET`
